const appname = "PCOS/PCOD App";
const appversion = "Version 3.0.0";
const credits = "@Sarita B.K.";
const email = "Email";
const emailHint = "Sarita@Admin.com";
const password = "password";
const passwordHint = "******";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Sarita B.K.";
const forgetPass = "Forget Password";
const login = "Log in";
const signup = "Sign Up";
const createnewAccount = "or, create a new account";
const loginWidth = "Log in with";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms and Conditions";
const alreadyHaveAccount = "Already have an account?";
const home = "home";
const symptomsTracker = "SymsTrack";
const diagnosis = "Diagnosis";
const resources = "Resources";
const profile = "Profile";
const searchanything = "search anything About Pcos/Pcod...",
    events = "Events",
    expertadvices = "Expert Advices",
    dashboard = "Health Dashboard",
    challenges = "Fitness Chlgs",
    success = "Success Stories",
    surveys = "Polls & surveys",
    features = "Balance Products";

const menstrualCalendar = "calendar";
const healthTips = "Community Supports";
const report = "Reports and Analysis ";
const bloodtest = "Blood Test remainder";
const stressmanagement = "Stress management";
